### ISSUE TITLE
Examples on ESP8266

### ISSUE THREAD

**Issue by idanmalul** [sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library#11]
Hi, 

I am trying to run your examples on ESP8266 nodemcu , and got error. 
There are changes which needed when using ESP8266 ? 
There is another implementation for ESP ? what could be the problem? 

Please advise.
Idan.

**Comment by santaimpersonator** [comment]
Could you provide more information... like what exactly is the error?

Secondly, those boards are incompatible. The ESP8266 uses 3.3V logic and the RFID shield uses 5V logic... you should use a logic level converter to avoid damaging your board.

**Comment by alex-prosh** [comment]
The SoftwareSerial library does not work with ESP modules. Use hardware serial instead.

**Comment by santaimpersonator** [comment]
@alex-prosh Thank you for your insight into the problem.

@idanmalul Another option is to use the [EspSoftwareSerial library](https://github.com/plerup/espsoftwareserial).

I am going to close this issue since there hasn't been much activity on it.
