### ISSUE TITLE
FATAL error

### ISSUE THREAD

**Issue by Shareek81** [sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library#18]
CODE :
          import com.fazecast.jSerialComm.*;
public class test
{
	static{
		  // System.setProperty("java.library.path", "F:\\Ur Challange\\UHF RFID fixed reader\\UHF\\SDK\\java\\jSerialComm-master\\src\\main\\resources\\Windows\\x86_64");
		   System.loadLibrary("jSerialComm");
		  }
	//static public native test[] getCommPorts();
	public static void main(String[] args) {
		SerialPort[] s=SerialPort.getCommPorts();
		//System.out.println(s[0]);
	}
}

ERROR :    ( Compiled Successfully)
         Could not locate or access the native jSerialComm shared library.
If you are using multiple projects with interdependencies, you may need to fix your build settings to ensure that library resources are copied properly.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006ffefa96, pid=4860, tid=0x000000000000349c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x15fa96]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# F:\Ur Challange\UHFRFIDfixedreader\UHF\SDK\java\jSerialComm-master\src\main\java\hs_err_pid4860.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by nseidle** [comment]
Hi - This repo is for the Arduino library to support the reader. Looks like you're using a different language than Arduino. Sorry, we can only support Arduino at the moment.
