### ISSUE TITLE
Reading Tag EPC in ASCII?

### ISSUE THREAD

**Issue by callen5914** [sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library#9]
I am reading through the constant_read.ino file and I see we the code will return the HEX of each byte. My question is, how do we read ASCII data?

Say I have a tag name TestTrackTag01, ...02, ...03 and so on? Not really something wrong in code just my lack of knowledge.

**Comment by nseidle** [comment]
You can test spots against ASCII for example:

    if(nano.msg[31] == 'T' && nano.msg[32] == 'e')

but this is a bit tedious. There are ways to convert an array to a string and then test against that string. If I knew everything in the EPC was visible ASCII I might do it this way:

    String myEPC = "";
    for (byte x = 0 ; x < tagEPCBytes ; x++)
    {
      myEPC += nano.msg[31 + x];
    }

   if(myEPC == "Tag2") Serial.print("Tag 2 found!");

This is pseudo code and probably won't work but you get the idea.
